package RDA_vocabulary;

#Used by UClint_RDA.pm to check RDA controlled vocabulary
#Correct 19/07/13 Paul T-C  


use strict;
require Exporter;

our @ISA = qw(Exporter);
our @EXPORT_OK = qw(%contenta %contentb %mediaa %carriera @rel_des);

#Content type 336
#
#336a -> leader position 06 (type of material)
our %contenta = (
'cartographic dataset' => 'ef',
'cartographic image' =>'ef',
'cartographic moving image' => 'ef',
'cartographic tactile image' => 'ef',
'cartographic tactile three-dimensional form' => 'ef',
'cartographic three-dimensional form' => 'ef',
'computer dataset' => 'm',
'computer program' => 'm',
'notated movement' => 'at',
'notated music' => 'cd',
'performed music' => 'j',
'sounds' => 'i',
'spoken word' => 'i',
'still image' => 'k',
'tactile image' => 'k',
'tactile notated music' => 'cd',
'tactile notated movement' => 'at',
'tactile text' => 'at',
'tactile three-dimensional form' => 'r',
'text' => 'at',
'three-dimensional form' => 'r',
'three-dimensional moving image' => 'g',
'two-dimensional moving image' => 'g',
'other' => 'op',
'unspecified' => '[a-z]',
);

#336b -> 336a
our %contentb = (
'crd' => 'cartographic dataset',
'cri' => 'cartographic image',
'crm' => 'cartographic moving image',
'crt' => 'cartographic tactile image',
'crn' => 'cartographic tactile three-dimensional form',
'crf' => 'cartographic three-dimensional form',
'cod' => 'computer dataset',
'cop' => 'computer program',
'ntv' => 'notated movement',
'ntm' => 'notated music',
'prm' => 'performed music',
'snd' => 'sounds',
'spw' => 'spoken word',
'sti' => 'still image',
'tci' => 'tactile image',
'tcm' => 'tactile notated music',
'tcn' => 'tactile notated movement',
'tct' => 'tactile text',
'tcf' => 'tactile three-dimensional form',
'txt' => 'text',
'tdf' => 'three-dimensional form',
'tdm' => 'three-dimensional moving image',
'tdi' => 'two-dimensional moving image',
'xxx' => 'other',
'zzz' => 'unspecified',
);

#Media type 337
#337a -> 337b = 007 position 00
our %mediaa= (
'audio' => 's',
'computer' => 'c',
'microform' => 'h',
'microscopic' => 'p',
'projected' => 'g',
'stereographic' => 'e',
'unmediated' => 'n', 
'video' => 'v',
'other' => 'x',
'unspecified' => 'z',
);


#Carrier 338
#338a -> 338b 
our %carriera = (
'audio cartridge' => 'sg',
'audio cylinder' => 'se',
'audio disc' => 'sd',
'sound track reel' => 'si',
'audio roll' => 'sq',
'audiocassette' => 'ss',
'audiotape reel' => 'st',
'computer card' => 'ck',
'computer chip cartridge' => 'cb',
'computer disc' => 'cd',
'computer disc cartridge' => 'ce',
'computer tape cartridge' => 'ca',
'computer tape cassette' => 'cf',
'computer tape reel' => 'ch',
'online resource' => 'cr',
'aperture card' => 'ha',
'microfiche' => 'he',
'microfiche cassette' => 'hf',
'microfilm cartridge' => 'hb',
'microfilm cassette' => 'hc',
'microfilm reel' => 'hd',
'microfilm roll' => 'hj',
'microfilm slip' => 'hh',
'microopaque' => 'hg',
'microscope slide' => 'pp',
'film cartridge' => 'mc',
'film cassette' => 'mf',
'film reel' => 'mr',
'film roll' => 'mo',
'filmslip' => 'gd',
'filmstrip' => 'gf',
'filmstrip cartridge' => 'gc',
'overhead transparency' => 'gt',
'slide' => 'gs',
'stereograph card' => 'eh',
'stereograph disc' => 'es',
'card' => 'no',
'flipchart' => 'nn',
'roll' => 'na',
'sheet' => 'nb',
'volume' => 'nc',
'object' => 'nr',
'video cartridge' => 'vc',
'videocassette' => 'vf',
'videodisc' => 'vd',
'videotape reel' => 'vr',
'other' => 'z',
'unspecified' => 'zu',
);

#Relationship designators
#
our @rel_des = (
"architect",
"landscape architect",
"artist",
"sculptor",
"author",
"librettist",
"lyricist",
"screenwriter",
"cartographer",
"choreographer",
"compiler",
"composer",
"designer",
"enacting jurisdiction",
"filmmaker",
"interviewee",
"interviewer",
"inventor",
"photographer",
"praeses",
"programmer",
"respondent",
"addressee",
"appellant",
"appellee",
"consultant",
"court governed",
"dedicatee",
"dedicator",
"defendant",
"degree granting institution",
"degree supervisor",
"director",
"film director",
"radio director",
"television director",
"director of photography",
"honouree",
"host institution",
"issuing body",
"judge",
"jurisdiction governed",
"plaintiff",
"producer",
"film producer",
"radio producer",
"television producer",
"production company",
"sponsoring body",
"abridger",
"animator",
"arranger of music",
"art director",
"choreographer (expression)",
"composer (expression)",
"costume designer",
"court reporter",
"draftsman",
"editor",
"editor of compilation",
"editor of moving image work",
"illustrator",
"interviewee (expression)",
"interviewer (expression)",
"musical director",
"performer",
"actor",
"voice actor ",
"commentator",
"conductor",
"dancer",
"host",
"instrumentalist",
"moderator",
"narrator",
"on-screen presenter",
"panelist",
"puppeteer",
"singer",
"speaker",
"storyteller",
"teacher",
"presenter",
"production designer",
"recording engineer",
"recordist",
"stage director",
"surveyor",
"transcriber",
"translator",
"writer of supplementary textual content",
"writer of added commentary",
"writer of added text",
"writer of added lyrics",
"writer of introduction ",
"writer of preface",
"book designer",
"braille embosser",
"caster",
"collotyper",
"engraver",
"etcher",
"lithographer",
"platemaker",
"printer",
"printmaker",
"broadcaster",
"film distributor",
"current owner",
"depositor",
"former owner",
"donor",
"seller",
"annotator",
"autographer",
"binder",
"curator",
"collection registrar",
"collector",
"dedicatee of item",
"honouree of item",
"illuminator",
"inscriber",
"restorationist ",
);